name: Tailscale-Windows-RDP

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Download & Install Tailscale
        run: |
          # Download MSI installer
          Invoke-WebRequest https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe -OutFile tailscale-setup.exe
          # Install secara silent
          Start-Process -FilePath .\tailscale-setup.exe -ArgumentList "/quiet /norestart" -Wait
          
      - name: Connect to Tailscale
        shell: pwsh
        run: |
          # Jalankan tailscale login menggunakan OAuth
          & 'C:\Program Files\Tailscale\tailscale.exe' up --authkey "tskey-client-${{ secrets.TS_CLIENT_ID }}-${{ secrets.TS_CLIENT_SECRET }}?ephemeral=true"
        
      - name: Enable RDP
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
          Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

      - name: Keep Alive
        run: |
          $ip = & 'C:\Program Files\Tailscale\tailscale.exe' ip -4
          Write-Host "Koneksi Berhasil!"
          Write-Host "IP Tailscale kamu: $ip"
          Write-Host "Gunakan IP di atas untuk RDP."
          Start-Sleep -Seconds 21600
